### PR TITLE
Allow comparing Nullable via Expression.Constant

### LINKED ISSUE #25: Filtering fails on nullable integers
Hi!
Great project! I've noticed that attempting to filter on fields of type `int?` breaks Sieve.

On my model I have:
```
[Sieve(CanFilter = true, CanSort = true)]
public int? CategoryId { get; set; }
```
I'd expect to be able to `&filters=CategoryId==5` but instead that results in all of the results being sent instead of my filtered, paginated result.

### PR DESCRIPTION
**Pull request by zolrath**
Using `Expression.Constant` for `GetClosureOverConstant`. Came to this solution from reading:  http://bradwilson.typepad.com/blog/2008/07/creating-nullab.html

Closes #25

### CODE REVIEW

**Comment by zolrath** [comment]
`CategoryId==null` still fails with this method but it allows comparison of non null values.

**Comment by zolrath** [comment]
I can special case filtering for "null" fairly easily but it opens up a can of worms when it comes to things like string equality and `null`. Do we search for a string literal of "null" or a `null`?

This commit as-is doesn't attempt to address that but instead just allows us to perform value comparisons for nullable properties.

**Comment by Biarity** [comment]
Yeah I also agree we shouldn't allow `null` filtering for now, at least not until the parser is rewritten.

**Review by Biarity — APPROVED** [review]

**Review by Biarity — APPROVED** [review]
Looks good to me!

**Comment by Biarity** [comment]
Published to nuget as v2.1.1, thanks for your contributions!

**Comment by Shangshin-Liu** [comment]
How to filter with empty or null string ?

**Comment by SinghManvir** [comment]
> Yeah I also agree we shouldn't allow `null` filtering for now, at least not until the parser is rewritten.

Is this still the case? I have a Nullable Guid property and I want to get all rows where the value is NULL. Is this possible?

**Comment by drowhunter** [comment]
I have a nullable datetime and things are exploding

**Pull request merged**
