### PR TITLE
OrderByDynamic is modified to be able to handle inherited members...

### LINKED ISSUE #97: Interface based property registrations with custom naming are not working on sorts
Ref. commit: 5c2ef3773e69808def66c9ee489ea9e1ef40045e

Define the classes as below, only interfaces added and inheritance applied suitably:

    public interface IBaseEntity
    {
        int Id { get; set; }
        DateTimeOffset DateCreated { get; set; }
    }

    public class BaseEntity : IBaseEntity
    {
        public int Id { get; set; }

        [Sieve(CanFilter = true, CanSort = true)]
        public DateTimeOffset DateCreated { get; set; } = DateTimeOffset.UtcNow;
    }

    public interface IPost : IBaseEntity
    {
        string Title { get; set; }
        int LikeCount { get; set; }
        int CommentCount { get; set; }
        int? CategoryId { get; set; }
        bool IsDraft { get; set; }
        string ThisHasNoAttribute { get; set; }
        string ThisHasNoAttributeButIsAccessible { get; set; }
        int OnlySortableViaFluentApi { get; set; }
        Comment TopComment { get; set; }
        Comment FeaturedComment { get; set; }
    }

    public class Post : BaseEntity, IPost
    {

        [Sieve(CanFilter = true, CanSort = true)]
        public string Title { get; set; } = Guid.NewGuid().ToString().Replace("-", string.Empty).Substring(0, 8);

        [Sieve(CanFilter = true, CanSort = true)]
        public int LikeCount { get; set; } = new Random().Next(0, 1000);

        [Sieve(CanFilter = true, CanSort = true)]
        public int CommentCount { get; set; } = new Random().Next(0, 1000);

        [Sieve(CanFilter = true, CanSort = true)]
        public int? CategoryId { get; set; } = new Random().Next(0, 4);

        [Sieve(CanFilter = true, CanSort = true)]
        public bool IsDraft { get; set; }

        public string ThisHasNoAttribute { get; set; }

        public string ThisHasNoAttributeButIsAccessible { get; set; }

        public int OnlySortableViaFluentApi { get; set; }

        public Comment TopComment { get; set; }
        public Comment FeaturedComment { get; set; }
    }

Then add

            mapper
                .Property<IPost>(entity => entity.DateCreated)
                .CanSort()
                .HasName("CreateDate");

to `ApplicationSieveProcessor.MapProperties(...)`.

Add the test method:

        [TestMethod]
        public void InterfaceDefinedPropertyMappingSortingWorks_WithCustomName()
        {
            var model = new SieveModel()
            {
                Sorts = "-CreateDate"
            };

            var result = _processor.Apply(model, _posts.Select(post => post as IPost));
            Assert.AreEqual(4, result.Count());

            var posts = result.ToList();
            Assert.AreEqual(posts[0].Id, 3);
            Assert.AreEqual(posts[1].Id, 2);
            Assert.AreEqual(posts[2].Id, 1);
            Assert.AreEqual(posts[3].Id, 0);
        }

See it fails.

I can't verify the changes causing this, yet, but it has something to do with `GenerateLambdaWithSafeMemberAccess<TEntity>(...)` call. I haven't dove deep on this but I am pretty sure that above mentioned kind of logic is working with the version 2.3.3, since it is on a production environment. And the diff between previous commit (4cac27c22db5c7edb514a410321a3d74320e4b26) and this one (5c2ef3773e69808def66c9ee489ea9e1ef40045e) is centralising around that `GenerateLambdaWithSafeMemberAccess` method.

### PR DESCRIPTION
**Pull request by hasanmanzak**
- OrderByDynamic is modified to be able to handle inherited members, such as interface members.
- SieveProcessor is modified to pass propertyInfo to OrderByDynamic to avoid reattainment of propertyInfo required in Expression.MakeMemberAccess.
- SieveProcessor is modified to be able to handle possible multiple incompatible customMethods via AggregateException.
- Corresponding interfaces are generated for entities with related inheritance.
- ApplicationSieveProcessor is modified to include interface members.
- SieveCustomFilterMethods and SieveCustomSortMethod are modified to include interface related custom method modifications.
Interface accessed unit tests are added.

closed #97

### CODE REVIEW

**Comment by soroshsabz** [comment]
@a-patel Did you any plan to review PRs?

**Comment by a-patel** [comment]
I will check this @soroshsabz.

**Comment by hasanmanzak** [comment]
> 
> 
> I will check this @soroshsabz.

@a-patel Any update?

**Review by a-patel — APPROVED** [review]

**Comment by a-patel** [comment]
@hasanmanzak , Thanks for your contribution!

**Pull request merged**
