### PR TITLE
#80 added support for escaping pipe control characters

### PR DESCRIPTION
**Pull request by claytonandersen**
Using an escaped comma or pipe in a value filter causes Sieve to send the escape character in the filter expression. This PR removes the escape character when the filter is built.

### CODE REVIEW

**Comment by ITDancer13** [comment]
We have the same issue on our side. Thanks for your attempt to fix it 👍

**Review by ITDancer13 — APPROVED** [review]

**Review by nasirk49 — APPROVED** [review]

**Comment by hasanmanzak** [comment]
@claytonandersen Could you resolve the conflicts? I think there were other changes before this pr yet to be merged.

**Comment by ITDancer13** [comment]
@claytonandersen Thanks for your contribution. I've already fixed the comma issue when I merged the changes from my fork. Can you please rebase your branch and change the target to `releases/3.0.0`

**Review by hasanmanzak — APPROVED** [review]

**Comment by claytonandersen** [comment]
Hey, looks like this was done, sorry I didn't get back to it until today. The merge looks good though. Thanks @ITDancer13 @hasanmanzak !

**Pull request merged**
