### PR TITLE
Make ApplyFiltering, ApplySorting and ApplyPagination protected virtu…

### LINKED ISSUE #139: Make ApplyFiltering, ApplySorting and ApplyPagination protected virtual
Quick win as suggested in #138: "I think a quick fix to make this easier would be to make the ApplyPagination, ApplyFiltering, ApplySorting methods protected and virtual. This would let users inherit from SieveProcessor and only have to override the methods they care about changing."

### PR DESCRIPTION
**Pull request by ITDancer13**
Make ApplyFiltering, ApplySorting and ApplyPagination protected virtual.
Closes #139

### CODE REVIEW

**Review by hasanmanzak — APPROVED** [review]
It's ok. But, we know this would open the way to some veeery unpleasant dependencies in the future, right? As of very very breaking API changes...

**Comment by ITDancer13** [comment]
Mhm you're right. Didn't think about that point in this case. But I think we need to open Sieve. When I take a look at some of our projects, which are based on Sieve, we had to implement some ugly workarounds, too.

Pros and cons...

**Comment by hasanmanzak** [comment]
Tell me about it :) I had to write a veeery fat builder for multiple entities including using a runtime compiler..

**Review by Biarity — APPROVED** [review]
Hm I'm happy with this change, however my general outlook is to implement any extensions ourselves rather than declaring a "wontfix" and leaving developers to manually override these methods.

Eg. the skip/top request in #138 - rather than make Sieve more extensible through this PR, we can just implement skip/top as a core part of Sieve.

The reality is there is not an infinite amount of ways to sort/filter/paginate/select, there is only a few practical ways - so it might be worth us directly implementing them to keep quality up and uphold the "out of the box" claim in the readme! I'd be interesting in hearing about workarounds you guys have had to make as that's exactly what we should tackle :)

**Comment by ITDancer13** [comment]
I like the idea to put as much as possible to Sieve. Maybe we should think about splitting the SieveProcessor (which does most oft the work now) into smaller pieces to tackle it. But maybe we should start a discussion about "How to make Sieve more flexible" ;-)

But I think that Sieve should still be as extensible as possible. There will be edge cases which we won't support by our core implementation.

**Comment by Biarity** [comment]
I'm fully on board with splitting up the SieveProcessor - perhaps by separating the sorting, filtering, and pagination bits entirely. I think I saw an issue for it a while back but can't find it now

I think we should list up some scenarios that Sieve can't handle right now and use that to decide next steps, eg. #146

**Pull request merged**
