### PR TITLE
#111: pass filter values as parameters

### PR DESCRIPTION
**Pull request by alicak**
Solves issue #111.

With the same example as in the issue description, the generated query now is:

```
SELECT "e"."Id", "e"."Author", "e"."Name", "e"."YearPublished"
FROM "Books" AS "e"
WHERE "e"."Id" = @__constant_0
```

### CODE REVIEW

**Comment by ITDancer13** [comment]
@alicak thanks for your pull request. Can you please rebase your branch to solve the conflicts.

**Comment by ITDancer13** [comment]
I take care of resolving the conflicts and then check the result.

**Comment by ITDancer13** [comment]
Conflict resolved. Checked manually in Sieve.Sample application by applying a Title filter.

image

LGTM

@hasanmanzak @Biarity What do you think?

Unfortunately I didn't find a good way to add a test for it. Any suggestions?

**Comment by hasanmanzak** [comment]
Something like this? https://github.com/dotnet/efcore/issues/3361#issuecomment-163753139

**Review by hasanmanzak — APPROVED** [review]
looks ok to me.. LG or not :)

**Pull request merged**
