### PR TITLE
Disable the use of the nullable type expression for sorting

### PR DESCRIPTION
**Pull request by HBTeun**
MongoDB has issues with the expression created when sorting on nullable types.
So I created an option to disable it.

If there is anything I need to do to improve it please let us know

### CODE REVIEW

**Comment by HBTeun** [comment]
I think this is also an option for #110

**Review by Mastermindzh — APPROVED** [review]
Looks good. All the comments from our [internal review](https://github.com/Inforitnl/Sieve/pull/2) have been resolved.

**Review by hasanmanzak — APPROVED** [review]
LGTM

**Comment by Mastermindzh** [comment]
Any window for release?
We're currently building and using our own but would love to get back on the official version 😄

**Comment by hasanmanzak** [comment]
If no feedback is provided I'll merge the PR on next Monday, March 28th, 2022

**Comment by Mastermindzh** [comment]
@hasanmanzak, if you could, please 😄.

Will there also be a new version published to nuget right away?

**Comment by hasanmanzak** [comment]
> @hasanmanzak, if you could, please 😄.
> 
> Will there also be a new version published to nuget right away?

Yes. It's already been published.

**Pull request merged**
