### PR TITLE
stop excluding null values when filtering using notEqual

### PR DESCRIPTION
**Pull request by AnasZakarneh**
ApplyFiltering is modified to be able to return null values when the operator is not equal.
if we have [{categoryId=null}, {categoryId=1}, {categoryId=2}]
and we aplly "categoryId!=2" the result should be [{categoryId=null}, {categoryId=1}] not [{categoryId=1}]

### CODE REVIEW

**Comment by hasanmanzak** [comment]
Equality with null values behaves differently. If you apply `categoryId!=2` to `[{categoryId=null}, {categoryId=1}, {categoryId=2}]` the result set should **NOT** be `[{categoryId=null}, {categoryId=1}]`. It is exactly `[{categoryId=1}]`.

`null` is not a `value` thus a `null value` construct is needed in general. That is why every other DBMS has some kind of null-check function to cope with this. MsSQL has `ISNULL(exp, val)`, Oracle has `NVL(exp, val)` etc.

I'm voting not to approve this PR. @ITDancer13 @Biarity

**Comment by ITDancer13** [comment]
Hm interesting - my first thought was 'Yes, I agree with @hasanmanzak' but I'm not sure about it anymore. 

If we would do the same on a list via Linq it would return `[{categoryId=null}, {categoryId=1}]` BUT if we're executing a SQL statement on SQL Server only `[{categoryId=1}]` would be returned.

@Biarity what do you think?

If we would accept it, it should go to v3.

**Comment by hasanmanzak** [comment]
I still vote for no. Because, if we approve this, it'll be a breaking change for LINQ-to-SQL implementations. LINQ-to-Object implementations however, will benefit I'm sure, but still, we need to keep the maximum compatibility.

I'm OK with a switch based configuration, though.

**Comment by Biarity** [comment]
I prefer merging this in, because the default behvaiour we have now is not 100% expected behviour for the average developer and will probably result in a few bugs, plus we don't have explicit null comparison operators.

Let's have nulls included, but adding a configuration option to allow turning this feature off for devs who know what they're doing.

**Comment by ITDancer13** [comment]
@AnasZakarneh You accidentally merged master into your branch and not the releases/2.5.0
Templates and Readme should not be part of this PR.

**Review by ITDancer13 — CHANGES_REQUESTED** [review]
ISSUE_TEMPLAE/bug_report.md
ISSUE_TEMPLATE/config.yml
README.md

should not be part of this PR

**Comment by AnasZakarneh** [comment]
> ISSUE_TEMPLAE/bug_report.md
> ISSUE_TEMPLATE/config.yml
> README.md
> 
> should not be part of this PR

**Comment by AnasZakarneh** [comment]
@ITDancer13 , sorry it was by mistake.
it should be synced with release/2.5 now

**Comment by ITDancer13** [comment]
@AnasZakarneh Thanks for merging release/2.5.0

As you can see there were some discussion with @Biarity and @hasanmanzak about this change. Can you please add the suggested configuration option to enable / disable this feature. Default to should like it was before to get a non-breaking change for release 2.5.0

**Comment by AnasZakarneh** [comment]
@ITDancer13 Thanks for reviewing the PR.
just added the configuration option please check

**Review by ITDancer13 — APPROVED** [review]

**Pull request merged**
