### PR TITLE
Allow filtering and sorting for nested objects

### PR DESCRIPTION
**Pull request by jakoss**
This might not be the cleanest solution, and it does not work for attributes, but it's working fine for FluentAPI

### CODE REVIEW

**Review by Biarity — CHANGES_REQUESTED** [review]
Thanks for taking the time to help!

Unfortunately it does not compile on my machine, and so won't pass our unit tests.
 
Error: `CS0535	'SieveAttribute' does not implement interface member 'ISievePropertyMetadata.FullName'`

**Comment by Nekromancer** [comment]
Ok, now it passes all unit tests. 

Honestly i don't have a clue how could we make it work with annotations. Objects can be nested in many ways, and there's no way to figure it out and setup mappings for that. I think the only solution here is to leave annotations as they are and make nested objects available only for FluetApi

**Review by Biarity — APPROVED** [review]

**Comment by Biarity** [comment]
That's okay, I'll be looking more into this feature once I get the time. Otherwise it is working great for me, I'll add more tests and publish this in the next version.

**Comment by Arcturuss** [comment]
Looks like there's a bug in filtering nested fields.

When I filter by multiple columns using OR, like `name|email@=str`, inserting nested field breaks resulting SQL request: `OR` in SQL changes to `|` for all next clauses.

#### Example:
`filters = 'userName|email|firstName|lastName|phoneNumber@=test';`
correct SQL:
```
...
      WHERE ((((y."IsDeleted" = FALSE) AND (y."OrganizationId" IS NOT NULL AND (y."OrganizationId" = @__orgId_0))) AND (y."IsHidden" = FALSE)) AND (((((CASE
          WHEN STRPOS(y."UserName", 'test') > 0
          THEN TRUE::bool ELSE FALSE::bool
      END OR CASE
          WHEN STRPOS(y."Email", 'test') > 0
          THEN TRUE::bool ELSE FALSE::bool
      END) OR CASE
          WHEN STRPOS(y."FirstName", 'test') > 0
          THEN TRUE::bool ELSE FALSE::bool
      END) OR CASE
          WHEN STRPOS(y."LastName", 'test') > 0
          THEN TRUE::bool ELSE FALSE::bool
      END) OR CASE
          WHEN STRPOS(y."PhoneNumber", 'test') > 0
          THEN TRUE::bool ELSE FALSE::bool
      END) = TRUE)
...
```
`filters = 'userName|email|firstName|organization.Name|lastName|phoneNumber@=test';`
broken SQL:
```
...
      WHERE (((y."IsDeleted" = FALSE) AND (y."OrganizationId" IS NOT NULL AND (y."OrganizationId" = @__orgId_0))) AND (y."IsHidden" = FALSE)) AND ((((((CASE
          WHEN STRPOS(y."UserName", 'test') > 0
          THEN TRUE::bool ELSE FALSE::bool
      END OR CASE
          WHEN STRPOS(y."Email", 'test') > 0
          THEN TRUE::bool ELSE FALSE::bool
      END) OR CASE
          WHEN STRPOS(y."FirstName", 'test') > 0
          THEN TRUE::bool ELSE FALSE::bool
      END) | CASE
          WHEN STRPOS("y.Organization"."Name", 'test') > 0
          THEN TRUE::bool ELSE FALSE::bool
      END) | CASE
          WHEN STRPOS(y."LastName", 'test') > 0
          THEN TRUE::bool ELSE FALSE::bool
      END) | CASE
          WHEN STRPOS(y."PhoneNumber", 'test') > 0
          THEN TRUE::bool ELSE FALSE::bool
      END) = TRUE)
...
```

**Comment by Nekromancer** [comment]
Is that " sign before y here an copy error or actually generated sql?

**Comment by Arcturuss** [comment]
No, that's actually generated SQL.

Npgsql.EntityFrameworkCore.PostgreSQL 2.2.0
Npgsql.EntityFrameworkCore.PostgreSQL.Design 1.1.1
postgresql 11

Full message:
```
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (23ms) [Parameters=[@__orgId_0='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
      SELECT COUNT(*)::INT4
      FROM "AspNetUsers" AS y
      LEFT JOIN "Organizations" AS "y.Organization" ON y."OrganizationId" = "y.Organization"."Id"
      WHERE (((y."IsDeleted" = FALSE) AND (y."OrganizationId" IS NOT NULL AND (y."OrganizationId" = @__orgId_0))) AND (y."IsHidden" = FALSE)) AND ((((((CASE
          WHEN STRPOS(y."UserName", 'test') > 0
          THEN TRUE::bool ELSE FALSE::bool
      END OR CASE
          WHEN STRPOS(y."Email", 'test') > 0
          THEN TRUE::bool ELSE FALSE::bool
      END) OR CASE
          WHEN STRPOS(y."FirstName", 'test') > 0
          THEN TRUE::bool ELSE FALSE::bool
      END) | CASE
          WHEN STRPOS("y.Organization"."Name", 'test') > 0
          THEN TRUE::bool ELSE FALSE::bool
      END) | CASE
          WHEN STRPOS(y."LastName", 'test') > 0
          THEN TRUE::bool ELSE FALSE::bool
      END) | CASE
          WHEN STRPOS(y."PhoneNumber", 'test') > 0
          THEN TRUE::bool ELSE FALSE::bool
      END) = TRUE)
Npgsql.PostgresException (0x80004005): 42883: оператор не существует (operator doesn't exist): boolean | boolean
```

**Comment by Nekromancer** [comment]
Ok, that's very weird. Gonna take a look at this

**Comment by Arcturuss** [comment]
same with AND changing to &

**Comment by Biarity** [comment]
@Arcturuss Can you try adding an alias for `Organization.Name` that doesn't contain a dot? For example in mapper:
```C#
...
            .HasName("organisation_name");
```
Does this bug still occur?

**Comment by PurrfectME** [comment]
Hi @Biarity , Im using Sieve and I'm facing the following problem(probably I'm doing something incorrectly)

I have a relational database with a column which is just a JSON string {"key":"value"}
It converts to domain model which is like simple class wrapper which extends from Dictionary<string, string> 

image

When I retrieve this JSON string from db and mapping it to domain model and calling ApplyFilter
it fails with inner Sieve exception saying it's impossible to convert from string to StringI18N

Then I tried to override SievePropertyMapper MapProperties method like this
image


the previous problem disapperead but now it fails with error that "name" I provided in url query isn't found which is strange to me. I've even tried to add Sieve attribute with name but still the same.

Thanks

**Pull request merged**
