### PR TITLE
Allow filtering and sorting for nested objects based on attributes

### PR DESCRIPTION
**Pull request by timcope**

### CODE REVIEW

**Comment by timcope** [comment]
This extends the functionality started with [#45](https://github.com/Biarity/Sieve/issues/45) so that filtering and sorting works for nested objects solely based on SieveAttribute on properties.

**Comment by rodrigochapeta** [comment]
Hey @a-patel can we merge this one seems useful to not need custom setup

**Comment by a-patel** [comment]
Please resolve the conflicts.

**Comment by JuanCarbo** [comment]
Created a new Pull request resolving the conflicts

**Comment by hasanmanzak** [comment]
This is addressed in #117. @JuanCarbo please review that PR again?

**Pull request closed without merging**
